# Site settings
title: I'm Curtis
description: "Curtis's Blog"
url: 'http://chenbingshu.com/'
baseurl: '/'


author:
  name: 'Curtis'
  email: 477623879@qq.com
  twitter_username: Curtis_CBS
  facebook_username: CurtisCBS
  github_username:  CurtisCBS
  linkedin_username:  ''

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 5
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
timezone: Asia/Shanghai
